### ISSUE TITLE
Usage?

### ISSUE THREAD

**Issue by c2sandu** [StevenSalazarM/Termux-api-bluetooth#1]
Not really an issue, but I'm clueless about using it :)
I unzipped a compiled release in Termux and tried to launch "locally" the termux-api with arguments (of course it was not intended to be used like that, but at least I tried...).
Can you point me to the right direction - how to include these in the termux-api apk or other method to include your changes to the program on the Android phone application?
I was waiting for a way to connect to bluetooth devices from Termux for a long time, apparently it is not a priority for the developers for now...
Thanks,
Constantin

**Comment by realSquatter46** [comment]
Bump

**Comment by shanness** [comment]
Seems that the usage for each command is in the script.  Check the scripts?
https://github.com/StevenSalazarM/Termux-api-bluetooth/tree/master/scripts

**Comment by realSquatter46** [comment]
I mean how to install or activate

сб, 9 мар. 2019 г., 21:15 Craig <notifications@github.com>:

**Comment by shanness** [comment]
Hmm, yeah, good question!  I checked the pkg list and it's not available. 

@StevenSalazarM How do we install this on our phones?

I did a git clone of this repo to the phone, and sms-inbox works, but 
`$ sh termux-bluetooth-scaninfo ` just hangs.
It just runs this
`/data/data/com.termux/files/usr/libexec/termux-api BluetoothScanInfo`
I compared the `termux-api.c` file in your repo vs the termux-api one, and the only difference is this (typo bug?)
https://github.com/StevenSalazarM/Termux-api-bluetooth/commit/9df39b2df04b6787aa90f095610ba57a2030c727

Seems the reason it doesn't work is that the play store termux-api app doesn't ask for bluetooth permissions, so seems it would require a new termux-app play store app to make your scripts work?

Seems it would be best getting your scripts added to the official termux-api repo and ask them to update the play app to ask for bluetooth permission?

**Comment by StevenSalazarM** [comment]
In order to make termux-bluetooth-scaninfo work you should add a Java class to the official termux-api repository with the android-java classes and modify the Reciver class in order to make it accept termux-bluetooth-scaninfo and termux-bluetooth-connect. Then just install your own apk with the buetooth functions working and you can use this package to call them.

About [9df39b2](https://github.com/StevenSalazarM/Termux-api-bluetooth/commit/9df39b2df04b6787aa90f095610ba57a2030c727) it wasnt a typo bug, I had to install a termux-api apk modified and i had the classes in `com.termux.api/.TermuxApiReceiver`

I'm sorry for the dealy but all this was a project for univeristy and I didnt think it was going to be useful to anyone else.

If you have any other question let me know.

**Comment by lynxaegon** [comment]
A step by step install guide would be nice :)

LE:
I solved my requirements using Tasker and broadcasts from termux. 

I had a Nexus 5X lying around and i wanted to be able to remotely connect to a bluetooth soundbar and play music from youtube.

**Comment by StevenSalazarM** [comment]
I updated the usage section and released an apk [here](https://github.com/StevenSalazarM/termux-app-bluetooth/releases/tag/v0.1)
