### ISSUE TITLE
How to use? 

### ISSUE THREAD

**Issue by VoQZHD** [StevenSalazarM/Termux-api-bluetooth#2]

**Comment by StevenSalazarM** [comment]
I updated the readme file, you should just add a class BluetoothAPI to the java repository of termux-api and modify the Receiver class to make it call the real java functions, then generate an apk from your modified project, install it and now you should be able to use termux-blueooth-scaninfo and termux-bluetooth-connect in the termux console

**Comment by StevenSalazarM** [comment]
i'm so sorry for the delay

**Comment by arnoudkooi** [comment]
@StevenSalazarM This looks great but seems I'm not savvy enough to get this going. Would you have a more detailed walkthrough, or an APK?

**Comment by StevenSalazarM** [comment]
@arnoudkooi I do have an apk but it doesnt have the Java code inside BluetoothAPI.java for Bluetooth scan and connect since it was not requested to me (my java functions are empty). Atm it just adds termux-bluetooth-connect and termux-bluetooth-scaninfo to the termux-api-package function calls (and performs some commands requested for a particular case). Since I see that people are interested in this repository I will start to work on the Java code for the bluetooth scan at the end of July (I'm busy at the moment).

**Comment by arnoudkooi** [comment]
Appreciate it! I'll watch this repo, thanks!

**Comment by StevenSalazarM** [comment]
I updated the usage section and released an apk [here](https://github.com/StevenSalazarM/termux-app-bluetooth/releases/tag/v0.1), I haven't completed the termux-bluetooth-connect but feel free to introduce your own code in BluetoothAPI.java, also you can modify the code releated to termux-bluetooth-scaninfo if you want more info to be shown
